services:
  postgres:
    image: postgres:17
    container_name: ai-study-buddy-postgres
    restart: always
    environment:
      POSTGRES_DB: ai_study_buddy
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


  chroma:
    image: chromadb/chroma
    container_name: study_buddy_chroma
    restart: always
    ports:
      - "8001:8000"
    volumes:
      - chromadata:/chroma/chroma   

volumes:
  postgres_data:
  chromadata: